### ISSUE TITLE
Add support for other event based systems.

### ISSUE THREAD

**Issue by johnhenning** [airtai/fastkafka#285] opened 2023-05-15 13:17 UTC
It would be great if Kafka could be abstracted away so that other message brokers, pub-sub or event based systems could be used, ie

- rabbitmq
- zeromq
- etc

Having an interface that is AsyncAPI compliant could be a good starting point.

**Comment by Sternakt** [comment] 2023-05-15 13:54
Hi,

This is something we strive to, you can find the issue here: #139 

The first step is to abstract FastKafka so that underlying kafka back-ends can be interchangeable (at the moment we are using AIOKafka) and the issue has been opened here: #259 . This is actually planned to be done in this sprint, so you should see some progress soon :)
Next step is to abstract it so that it can be used with other message brokers such as rabbitmq, you can expect this to start after the first step is completed, probably in the next sprint (beginning of June).

**Comment by Sternakt** [comment] 2023-05-19 06:22
Closing this as it's a duplicate of #139

**Closed by Sternakt** 2023-05-19 06:22 UTC
Labels: duplicate
