### ISSUE TITLE
Incorrect AsyncAPI docs path on "fastkafka docs serve" command

### ISSUE THREAD

**Issue by Gerleff** [airtai/fastkafka#322] opened 2023-05-24 14:40 UTC
Hi!
Seems like a bug.

Assigned root_path at FastKafka

```
kafka_app = FastKafka(
    ...
    root_path=(settings.PROJECT.SOURCE_PATH / "service/connectors/queue").resolve(),
    ...
)
```

Logs on execution "fastkafka docs serve ...":
```
Done! ✨
Check out your shiny new generated files at ..../src/service/connectors/queue/asyncapi/docs.

Unexpected internal error: [Errno 2] No such file or directory: 'asyncapi/docs/'
```

**Comment by Sternakt** [comment] 2023-05-25 06:27
Found the issue, should be easily fixable, the problem is this line in the _cli_docs. It sould take the app root path into consideration.
[(https://github.com/airtai/fastkafka/blob/main/fastkafka/_cli_docs.py#L91)](https://github.com/airtai/fastkafka/blob/367dc7671a7f05065bdf386c914a0e46a9026d46/fastkafka/_cli_docs.py#L91)

This is planned to be fixed in the RC tommorow.

**Closed** 2023-05-29 07:47 UTC
Labels: bug

**Comment by Gerleff** [comment] 2023-06-01 08:01
Thanks for fix!
